/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
import type * as test from "./test";
export type { test };
export type { SimpleSwap } from "./SimpleSwap";
