/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISimpleSwap__factory } from "./ISimpleSwap__factory";
export { ISimpleSwapEvent__factory } from "./ISimpleSwapEvent__factory";
