/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISimpleSwap } from "./ISimpleSwap";
export type { ISimpleSwapEvent } from "./ISimpleSwapEvent";
