/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interface from "./interface";
export * as test from "./test";
export { SimpleSwap__factory } from "./SimpleSwap__factory";
